controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.609
    wheel_radius: 0.127

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 30.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true  # Simulated odometry (no real sensors)
    enable_odom_tf: true  # Let the controller publish odom -> base_link tf

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.2
    linear.x.min_velocity: -0.2
    linear.x.max_acceleration: 0.8
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.4
    angular.z.min_velocity: -0.4
    angular.z.max_acceleration: 1.6
    angular.z.min_acceleration: -1.6
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0