<?xml version="1.0"?>
<robot name="sweeper" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="intertial_macros.xacro"/>

  <!-- Define robot constants -->
  <xacro:property name="chassis_width" value="0.8636"/> <!--34"-->
  <xacro:property name="chassis_length" value="0.889"/>  <!--35"-->
  <xacro:property name="chassis_height" value="0.527"/> <!--20.75"-->
  <xacro:property name="chassis_mass" value="5"/>

  <xacro:property name="wheel_radius" value="0.127"/> <!--5"-->
  <xacro:property name="wheel_thickness" value="0.0823"/> <!--3.25"-->
  <xacro:property name="wheel_offset_y" value=".457"/>  <!--18"-->
  <xacro:property name="wheel_offset_z" value="0.0"/> <!--not used-->
  <xacro:property name="wheel_offset_x" value="0.0"/> <!--not used-->
  <xacro:property name="wheel_mass" value=".5"/>

  <xacro:property name="caster_wheel_mass" value=".2"/>
  <xacro:property name="caster_wheel_radius" value="0.0762"/> <!--3"-->
  <xacro:property name="caster_wheel_offset_z" value="0.0445"/> <!-- (1.75") lowest point of chassis to center of caster wheel-->
  <xacro:property name="caster_wheel_offset_x" value=".597"/>
  
  <!-- chasis bottom point is the back bottom metal frame near the motors -->
  <!-- mass inaccurate, only matters for simulation -->

  <!-- colors -->
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>
  <material name="orange">
    <color rgba="1 .3 .1 1" />
  </material>
  <material name="blue">
    <color rgba=".2 .2 1 1" />
  </material>
  <material name="black">
    <color rgba="0 0 0 1" />
  </material>
  <material name="red">
    <color rgba="1 0 0 1" />
  </material>

  <!-- base link-->
  <link name="base_link"/>

  <link name="base_footprint"/>

  <!-- base_footprint link-->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- chassis link -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-.0635 0 -.0953"/>
  </joint>

  <link name="chassis">
    <visual>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <!-- LEFT WHEEL LINK -->
  <joint name="left_wheel_joint" type="continuous"> <!-- change back to continuous-->
      <parent link="base_link"/>
      <child link="left_wheel"/>
      <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
      <axis xyz="0 0 1"/>
  </joint>

  <link name="left_wheel">
      <visual>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
          </geometry>
          <material name="blue"/>
      </visual>
      <collision>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
          </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_wheel">
      <material>Gazebo/Blue</material>
  </gazebo>

  <!-- RIGHT WHEEL LINK -->
  <joint name="right_wheel_joint" type="continuous"> <!-- change back to continuous-->
      <parent link="base_link"/>
      <child link="right_wheel"/>
      <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
      <axis xyz="0 0 -1"/>
  </joint>

  <link name="right_wheel">
      <visual>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
          </geometry>
          <material name="blue"/>
      </visual>
      <collision>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
          </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <gazebo reference="right_wheel">
      <material>Gazebo/Blue</material>
  </gazebo>

  <!-- CASTER WHEEL LINK -->
  <joint name="caster_wheel_joint" type="fixed">
      <parent link="chassis"/>
      <child link="caster_wheel"/>
      <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
  </joint>

  <link name="caster_wheel">
      <visual>
          <geometry>
              <sphere radius="${caster_wheel_radius}"/>
          </geometry>
          <material name="white"/>
      </visual>
      <collision>
          <geometry>
              <sphere radius="${caster_wheel_radius}"/>
          </geometry>
      </collision>
      <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
  </link>

  <gazebo reference="caster_wheel">
      <material>Gazebo/White</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
  </gazebo>

</robot>
