amcl:
  ros__parameters:
    use_sim_time: true  # Use simulation time (true) or real time (false). Default: false
    alpha1: 0.1  # Odometry model noise. Default: 0.2
    alpha2: 0.1  # Odometry model noise. Default: 0.2
    alpha3: 0.1  # Odometry model noise. Default: 0.2
    alpha4: 0.1  # Odometry model noise. Default: 0.2
    #alpha5: 0.1  # Odometry model noise. Default: 0.2
    base_frame_id: "base_footprint"  # The frame ID of the robot base. Default: "base_footprint"
    beam_skip_distance: 0.5  # Distance to skip beams. Default: 0.5
    beam_skip_error_threshold: 0.9  # Error threshold for beam skipping. Default: 0.9
    beam_skip_threshold: 0.3  # Threshold for beam skipping. Default: 0.3
    do_beamskip: false  # Enable beam skipping. Default: false
    global_frame_id: "map"  # The frame ID of the global map. Default: "map"
    lambda_short: 0.1  # The exponential distribution parameter for short beams. Default: 0.1
    laser_likelihood_max_dist: 2.0  # Maximum distance for laser likelihood field model. Default: 2.0
    laser_max_range: -1.0  # Maximum range of the laser. Default: 100.0
    laser_min_range: -1.0  # Minimum range of the laser. Default: -1.0
    laser_model_type: "likelihood_field"  # The type of laser model to use. Default: "likelihood_field"
    max_beams: 60  # Maximum number of beams to use for AMCL. Default: 60
    max_particles: 2000  # Maximum number of particles for AMCL. Default: 2000
    min_particles: 500  # Minimum number of particles for AMCL. Default: 500
    odom_frame_id: "odom"  # The frame ID of the odometry frame. Default: "odom"
    pf_err: 0.05  # Error threshold for the particle filter. Default: 0.05
    pf_z: 0.99  # Likelihood threshold for resampling particles. Default: 0.99
    recovery_alpha_fast: 0.1  # Recovery alpha fast parameter for AMCL. Default: 0.0
    recovery_alpha_slow: 0.001  # Recovery alpha slow parameter for AMCL. Default: 0.0
    resample_interval: 1  # Interval for resampling particles. Default: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # The type of robot motion model. Default: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5  # Rate to save the pose to file. Default: 0.5
    sigma_hit: 0.2  # Standard deviation for the hit model. Default: 0.2
    tf_broadcast: true  # Enable TF broadcasting. Default: true
    transform_tolerance: 1.0  # Transform tolerance in seconds. Default: 1.0
    update_min_a: 0.1  # Minimum update angle for AMCL. Default: 0.2
    update_min_d: 0.1  # Minimum update distance for AMCL. Default: 0.25
    z_hit: 0.5  # Weight for the hit part of the laser model. Default: 0.5
    z_max: 0.05  # Weight for the max part of the laser model. Default: 0.05
    z_rand: 0.5  # Weight for the random part of the laser model. Default: 0.5
    z_short: 0.005  # Weight for the short part of the laser model. Default: 0.005
    scan_topic: scan_filtered  # The topic name for incoming laser scans. Default: scan