<?xml version="1.0"?>
<robot name="sucky" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="intertial_macros.xacro"/>

  <!-- Define robot constants -->
  <xacro:property name="chassis_width" value="0.67"/> 
  <xacro:property name="chassis_length" value="0.69"/> 
  <xacro:property name="chassis_height" value="1.26"/> 
  <xacro:property name="chassis_mass" value="5"/>

  <xacro:property name="wheel_radius" value="0.127"/> 
  <xacro:property name="wheel_thickness" value="0.038862"/> 
  <xacro:property name="wheel_offset_y" value=".287147"/>  
  <xacro:property name="wheel_offset_z" value="0.0"/> <!--not used-->
  <xacro:property name="wheel_offset_x" value="0.0"/> <!--not used-->
  <xacro:property name="wheel_mass" value=".5"/>

  <!-- <xacro:property name="caster_wheel_mass" value=".2"/>
  <xacro:property name="caster_wheel_radius" value="0.0762"/> 
  <xacro:property name="caster_wheel_offset_z" value="0.0445"/>
  <xacro:property name="caster_wheel_offset_x" value=".597"/> -->
  
  <xacro:property name="omni_wheel_mass" value=".2"/>
  <xacro:property name="omni_wheel_radius" value="0.0635"/> <!-- 2.5"-->
  <xacro:property name="omni_wheel_thickness" value="0.04"/> 
  <xacro:property name="omni_wheel_offset_z" value="0.0635"/> <!-- (2.5") center of wheel to center of main axle-->
  <xacro:property name="omni_wheel_offset_x" value="0.2406396"/> <!-- (9.474") center of wheel to center of main axle-->
  <xacro:property name="omni_wheel_offset_y" value="0.2752344"/> <!-- (10.836") center of wheel to center of main axle -->

  <!-- chasis bottom point is the back bottom metal frame near the motors -->
  <!-- mass inaccurate, only matters for simulation -->

  <!-- colors for RViz visualization-->
  <material name="orange">
    <color rgba="1 .3 .1 0.7" />
  </material>
  <material name="black">
    <color rgba="0 0 0 0.7" />
  </material>

<!-- base_footprint -->
<link name="base_footprint"/>

<!-- base link -->
<link name="base_link"/>

<joint name="base_footprint_joint" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
</joint>

  <!-- chassis link -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-.0635 0 -.0953"/>
  </joint>

  <link name="chassis">
    <visual>
      <!-- <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 ${pi/2}"/> -->
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="file://$(find sucky_bringup)/meshes/sucky_reduced_4mb.stl" scale="0.1 0.1 0.1" />
      </geometry>
      <!-- RViz coloring -->
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/White</material>
  </gazebo>
  
  <!-- LEFT WHEEL LINK -->
  <joint name="left_wheel_joint" type="continuous"> <!-- change back to continuous-->
      <parent link="base_link"/>
      <child link="left_wheel"/>
      <origin xyz="0 ${wheel_offset_y} 0" rpy="0 0 0" />
      <axis xyz="0 1 0"/>
  </joint>

  <link name="left_wheel">
      <visual>
          <geometry>
              <!-- <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/> -->
              <mesh filename="file://$(find sucky_bringup)/meshes/Big_Wheel.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <!-- RViz coloring -->
          <material name="black"/>
      </visual>
      <collision>
          <origin xyz="0 0.019431 0" rpy="${pi/2} 0 0"/>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
          </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
          <origin xyz="0 0.019431 0" rpy="${pi/2} 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_wheel">
      <material>Gazebo/Black</material>
  </gazebo>

  <!-- RIGHT WHEEL LINK -->
  <joint name="right_wheel_joint" type="continuous"> <!-- change back to continuous-->
      <parent link="base_link"/>
      <child link="right_wheel"/>
      <origin xyz="0 ${-wheel_offset_y} 0" rpy="0 0 ${pi}" />
      <axis xyz="0 -1 0"/>
  </joint>

  <link name="right_wheel">
      <visual>
          <geometry>
              <mesh filename="file://$(find sucky_bringup)/meshes/Big_Wheel.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="black"/>
      </visual>
      <collision>
          <origin xyz="0 0.019431 0" rpy="${pi/2} 0 0"/>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
          </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
          <origin xyz="0 0.019431 0" rpy="${pi/2} 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <gazebo reference="right_wheel">
      <material>Gazebo/Black</material>
  </gazebo>

  <!-- CASTER WHEEL LINK -->
  <!-- <joint name="caster_wheel_joint" type="fixed">
      <parent link="chassis"/>
      <child link="caster_wheel"/>
      <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
  </joint>

  <link name="caster_wheel">
      <visual>
          <geometry>
              <sphere radius="${caster_wheel_radius}"/>
          </geometry>
          <material name="black"/>
      </visual>
      <collision>
          <geometry>
              <sphere radius="${caster_wheel_radius}"/>
          </geometry>
      </collision>
      <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
  </link> -->

  <!-- LEFT OMNI WHEEL LINK -->
  <joint name="left_omni_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="left_omni_wheel"/>
      <origin xyz="${-omni_wheel_offset_x} ${omni_wheel_offset_y} ${-omni_wheel_offset_z}" rpy="0 0 0"/>
  </joint>

  <link name="left_omni_wheel">
      <visual>
          <geometry>
              <!-- <sphere radius="${omni_wheel_radius}"/> -->
              <mesh filename="file://$(find sucky_bringup)/meshes/Small_Wheel.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="black"/>
      </visual>
      <collision>
          <origin xyz="0 0.019431 0" rpy="${pi/2} 0 0"/>
          <geometry>
              <cylinder radius="${omni_wheel_radius}" length="${omni_wheel_thickness}"/>
          </geometry>
      </collision>
  </link>

  <gazebo reference="left_omni_wheel">
      <material>Gazebo/Black</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
  </gazebo>

  <!-- RIGHT OMNI WHEEL LINK -->
  <joint name="right_omni_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="right_omni_wheel"/>
      <origin xyz="${-omni_wheel_offset_x} ${-omni_wheel_offset_y} ${-omni_wheel_offset_z}" rpy="0 0 0"/>
  </joint>

  <link name="right_omni_wheel">
      <visual>
          <geometry>
              <!-- <sphere radius="${omni_wheel_radius}"/> -->
              <mesh filename="file://$(find sucky_bringup)/meshes/Small_Wheel.stl" scale="0.001 0.001 0.001" />
          </geometry>
          <material name="black"/>
      </visual>
      <collision>
          <origin xyz="0 0.019431 0" rpy="${pi/2} 0 0"/>
          <geometry>
              <cylinder radius="${omni_wheel_radius}" length="${omni_wheel_thickness}"/>
          </geometry>
      </collision>
  </link>    

  <gazebo reference="right_omni_wheel">
      <material>Gazebo/Black</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
  </gazebo>

</robot>
