ekf_filter_node:
  ros__parameters:

    frequency: 30.0
    print_diagnostics: true
    permit_corrected_publication: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    two_d_mode: true

    # values are x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az.

    # Optical Encoders
    odom0: "/diffbot_base_controller/odom"
    odom0_config: [true, true, false, #only using orientation
                   false, false, false,
                   false, false, false,
                   false, false, true, #yaw
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false
    odom0_pose_use_child_frame: false
    #odom0_pose_rejection_threshold: 0.55  # Adjusted to 0.05 for pose rejection threshold
    #odom0_twist_rejection_threshold: 0.55  # Adjusted to 0.05 for twist rejection threshold

    #MPU 9250 sensor
    imu0: "/imu/data_raw"
    imu0_config: [false, false, false,  # Don't use orientation
                  false, false, true,  # Don't use angular velocity
                  false, false, false,  # Don't use linear velocity
                  false, false, false,  # Don't use orientation velocity
                  true,  true,  false]    # Use linear acceleration x, y, z
    imu0_differential: false
    imu0_queue_size: 5
    imu0_remove_gravitational_acceleration: true
    # imu0_pose_rejection_threshold: 1.5                 # 
    # imu0_twist_rejection_threshold: 1.5                #
    # imu0_linear_acceleration_rejection_threshold: 1.5  #


